on:
  push:
  release:
    types: [published]

jobs:
  build-docker-image:
    name: Build RStudio and R docker image
    runs-on: ubuntu-latest
    env:
      RSTUDIO_VERSION: 1.2.5033
      R_VERSION: 3.6.3
      BASE_IMAGE: jupyter/minimal-notebook:54462805efcb
    steps:
    - name: Checkout source
      uses: actions/checkout@v1

    - name: Get release version (if it is a release)
      id: get_version
      if: github.event_name == 'release'
      run: echo ::set-env name=TAG::$(echo ${GITHUB_REF:10})

    - name: Get tag name (if it is not a release)
      id: get_tag
      if: github.event_name == 'push'
      run: echo ::set-env name=TAG::$(echo "${GITHUB_REF##*/}")

    - name: Build and publish Docker Image with RStudio ${{ env.RSTUDIO_VERSION }} and R ${{ env.R_VERSION }}
      id: build_base
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: odahu/odahu-rstudio
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        tags: ${{ env.TAG }}
        buildargs: RSTUDIO_VERSION=${{ env.RSTUDIO_VERSION }},R_VERSION=${{ env.R_VERSION }},BASE_IMAGE=${{ env.BASE_IMAGE }}
        cache: true

    - name: Build and publish extended Docker Image with RStudio ${{ env.RSTUDIO_VERSION }}, R ${{ env.R_VERSION }} and data science packages
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: odahu/odahu-rstudio-datascience
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        tags: ${{ env.TAG }}
        buildargs: BASE_RSTUDIO_IMAGE=odahu/odahu-rstudio:${{ steps.build_base.outputs.tag }}@sha256:${{ steps.build_base.outputs.digest }}
        cache: true
        dockerfile: datascience.Dockerfile

    

