on: [push]

jobs:
  build-docker-image:
    name: Build RStudio and R docker image
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v1

    - name: Build and publish Docker Image with RStudio 1.2.5033 and R 3.6.3
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: odahu/odahu-rstudio
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        tags: 1.2.5033r3.6.3
        buildargs: RSTUDIO_VERSION=1.2.5033,R_VERSION=3.6.3

